### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mrdwab** [mrdwab/koboloadeR#2]
- [ ] Explore options other than assign.
- [ ] Store login information in some way.
- [x] Add a progress bar to `get_me` (just add `progress()` in there).

**Comment by mrdwab** [comment]
If there are more functions that make it to the shiny apps, storing login might not be necessary.
